name: LiquidReg_env2
channels:
  - conda-forge
  - nodefaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.3.1
  - alsa-lib=1.2.14
  - anyio=4.9.0
  - aom=3.9.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=21.2.0
  - arpack=3.9.1
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.4
  - aws-c-io=0.21.2
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.33.1
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.15.0
  - azure-identity-cpp=1.11.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.10.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blosc=1.21.6
  - bokeh=3.7.3
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.19.0
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - charls=2.4.2
  - charset-normalizer=3.4.2
  - click=8.2.1
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - colorcet=3.1.0
  - comm=0.2.2
  - contourpy=1.3.2
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dask-core=2025.7.0
  - datashader=0.18.2
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - double-conversion=3.3.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.4
  - fqdn=1.5.1
  - freetype=2.13.3
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - glpk=5.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.2.0
  - h5py=3.13.0
  - harfbuzz=11.2.1
  - hdbscan=0.8.39
  - hdf5=1.14.6
  - holoviews=1.21.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - igraph=0.10.16
  - imagecodecs=2025.3.30
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - iniconfig=2.0.0
  - ipykernel=6.29.5
  - ipympl=0.9.7
  - ipython=8.37.0
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.24.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.8
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - jxrlib=1.1
  - keras=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lazy-loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - leidenalg=0.10.2
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libarrow=20.0.0
  - libarrow-acero=20.0.0
  - libarrow-dataset=20.0.0
  - libarrow-substrait=20.0.0
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.7
  - libclang13=20.1.7
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.14.1
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwloc=2.11.2
  - libhwy=1.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - liblapack=3.9.0
  - libleidenalg=0.11.1
  - libllvm20=20.1.7
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=20.0.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.5
  - libprotobuf=6.31.1
  - libre2-11=2025.07.22
  - libsodium=1.0.20
  - libsqlite=3.50.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libthrift=0.22.0
  - libtiff=4.7.0
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - linkify-it-py=2.0.3
  - llvmlite=0.44.0
  - locket=1.0.0
  - lz4-c=1.10.0
  - markdown=3.8.2
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mdit-py-plugins=0.5.0
  - mdurl=0.1.2
  - mistune=3.1.3
  - ml_dtypes=0.5.1
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - namex=0.1.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.12.0
  - notebook=7.3.1
  - notebook-shim=0.2.4
  - numba=0.61.2
  - numpy=2.1.3
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.2
  - optree=0.16.0
  - orc=2.1.3
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.1
  - pandocfilters=1.5.0
  - panel=1.7.5
  - param=2.2.1
  - parso=0.8.4
  - partd=1.4.2
  - patsy=1.0.1
  - pcre2=10.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.1.1
  - pixman=0.46.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - pluggy=1.6.0
  - prometheus-cpp=1.3.0
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=20.0.0
  - pyarrow-core=20.0.0
  - pycparser=2.22
  - pyct=0.5.0
  - pygments=2.19.2
  - pynndescent=0.5.13
  - pyparsing=3.2.3
  - pyside6=6.9.1
  - pysocks=1.7.1
  - pytest=8.4.0
  - python=3.10.18
  - python-fastjsonschema=2.21.1
  - python-igraph=0.11.9
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pyviz_comms=3.0.6
  - pywavelets=1.8.0
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - qhull=2020.2
  - qt6-main=6.9.1
  - rav1e=0.7.1
  - re2=2025.07.22
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - retrying=1.4.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.26.0
  - s2n=1.5.23
  - scikit-image=0.25.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.7
  - spatialpandas=0.5.0
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - svt-av1=3.0.2
  - tbb=2022.1.0
  - terminado=0.18.1
  - texttable=1.7.0
  - threadpoolctl=3.5.0
  - tifffile=2025.5.10
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - toolz=1.0.0
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250516
  - typing_extensions=4.14.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - uc-micro-py=1.0.3
  - umap-learn=0.5.7
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wayland=1.23.1
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - xarray=2025.6.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xyzservices=2025.4.0
  - yaml=0.2.5
  - zeromq=4.3.5
  - zfp=1.0.1
  - zlib=1.3.1
  - zlib-ng=2.2.4
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - aim==3.27.0
      - aim-ui==3.27.0
      - aimrecords==0.0.7
      - aimrocks==0.5.2
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.10.11
      - aiosignal==1.3.2
      - alembic==1.16.2
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - base58==2.0.1
      - boltons==25.0.0
      - boto3==1.39.2
      - botocore==1.39.2
      - cachetools==6.1.0
      - cattrs==25.1.1
      - cluster-tools==2.1.0
      # - connectomics==0.0.4.dev7+g7c3d838
      - cryptography==45.0.5
      - dataclasses-json==0.6.7
      - edt==3.0.0
      - edward2==0.0.3
      - fastapi==0.115.14
      - filelock==3.18.0
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - greenlet==3.2.3
      - httpx==0.27.2
      - jax==0.6.2
      - jaxlib==0.6.2
      - jmespath==1.0.1
      - loxun==2.0
      - mako==1.3.10
      - marshmallow==3.26.1
      - multidict==6.6.3
      - mypy-extensions==1.1.0
      - narwhals==1.45.0
      - natsort==8.4.0
      - networkx==3.2.1
      - nvidia-cublas-cu12==12.5.3.2
      - nvidia-cuda-cupti-cu12==12.5.82
      - nvidia-cuda-nvcc-cu12==12.5.82
      - nvidia-cuda-nvrtc-cu12==12.5.82
      - nvidia-cuda-runtime-cu12==12.5.82
      - nvidia-cudnn-cu12==9.3.0.75
      - nvidia-cufft-cu12==11.2.3.61
      - nvidia-curand-cu12==10.3.6.82
      - nvidia-cusolver-cu12==11.6.3.83
      - nvidia-cusparse-cu12==12.5.1.3
      - nvidia-nccl-cu12==2.23.4
      - nvidia-nvjitlink-cu12==12.5.82
      - opencv-python==4.11.0.86
      - pims==0.7
      - plotly==6.1.0
      - propcache==0.3.2
      - psutil==6.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - python-dateutil==2.8.2
      - python-dotenv==1.0.1
      - restrictedpython==8.0
      - rich==13.8.1
      - s3transfer==0.13.0
      - shellingham==1.5.4
      - slicerator==1.1.0
      - sofima==0.1
      - sqlalchemy==2.0.41
      - starlette==0.46.2
      - tensorflow==2.19.0
      - tensorstore==0.1.76
      - tf-keras==2.19.0
      - typer==0.12.5
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - universal-pathlib==0.2.6
      - uvicorn==0.35.0
      - webknossos==2.1.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wkw==1.1.24
      - wrapt==1.17.2
      - yarl==1.20.1
      - zipp==3.5.1
      - monai
      - MedPy
